[tool.poetry]
name = "examples"
version = "0.1.0"
description = ""
authors = ["Tanusha <tanusha20020@tut.by>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
